version: '3'



services:
  mysql:
    container_name: mysql
    image: mysql:8.2.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: mysql
      MYSQL_PASSWORD: admin
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=mysql', '--password=admin']
      interval: 3s
      timeout: 5s
      retries: 5
    ports:
      - '3306:3306'
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_DB_URL: 'jdbc:mysql://mysql:3306/keycloak'
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_USER: pawa
      KEYCLOAK_PASSWORD: pawa
    volumes:
      - ./imports:/opt/keycloak/data/import
    command:
      - 'start-dev --import-realm'
    ports:
      - '8081:8080'
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - 'mysql:mysql'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.4.3
    ports:
      - '19092:19092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.1.10
    hostname: schema-registry
    depends_on:
      - kafka
    ports:
      - '8089:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://localhost:19092
      SCHEMA_REGISTRY_DEBUG: 'true'

